# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Debug
platform: Any CPU
before_build:
- nuget restore %solutionFile%
build:
  project: GoogleAnalyticsTracker.sln
  verbosity: minimal
artifacts:
- path: GoogleAnalyticsTracker/bin/Debug/GoogleAnalyticsTracker.dll
  name: GoogleAnalyticsTracker.dll
